---
# --------------------------------

- name: "Set fact for aarch64 download path"
  ansible.builtin.set_fact:
    hashicorp_arch: "linux_arm"
  when: ansible_architecture == "aarch64"
  tags: [ct-hashicorp]

- name: "Set fact for x86_64 download path"
  ansible.builtin.set_fact:
    hashicorp_arch: "linux_amd64"
  when: ansible_architecture == "x86_64"
  tags: [ct-hashicorp]

- name: "Make staging directory"
  ansible.builtin.file:
    state: directory
    path: "{{ hashicorp_dir_staging }}"
    mode: "0755"
  tags: [ct-hashicorp]

- name: "Make main directories"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0755"
  loop: "{{ hashicorp_dirs }}"
  become: true
  tags: [ct-hashicorp]

- name: "Include tasks (FF)"
  ansible.builtin.include_tasks:
    file: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version.split('.')[0] }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - default.yml
      paths:
      - "tasks"
  tags: [ct-hashicorp]

# --------------------------------
...
