---
- name: 'make staging directory'
  ansible.builtin.file:
    state: directory
    path: '{{hashicorp_dir_staging}}'
    mode: '0755'
  tags: [ct-hashicorp]

- name: 'make main directories'
  ansible.builtin.file:
    state: directory
    path: '{{item}}'
    owner: root
    group: root
    mode: '0755'
  loop: '{{hashicorp_dirs}}'
  become: true
  tags: [ct-hashicorp]

- name: 'installed required packages'
  ansible.builtin.apt:
    name: '{{hashicorp_dependent_pkgs}}'
    state: present
  become: true
  tags: [ct-hashicorp]
...
