---
# --------------------------------

- name: "RedHat : Install packages"
  ansible.builtin.yum:
    name: "{{ hashicorp_pkgs_common.redhat }}"
    state: present
  become: true
  tags: [ct-hashicorp]

# --------------------------------
...
