---
# --------------------------------

- name: "Install Debian packages"
  ansible.builtin.apt:
    name: "{{ hashicorp_pkgs_common.debian }}"
    state: present
  become: true
  tags: [ct-hashicorp]

# --------------------------------
...
